describe("momiji-highlight", function()
  local momiji = require("momiji")
  it("should run normaly", function()
    assert.has_no.errors(function()
      momiji.highlight("testhi", {})
    end)
    assert.has_no.errors(function()
      momiji.highlight("testhi", { fg = momiji.palette.black })
    end)
    assert.has_no.errors(function()
      momiji.highlight("testhi", { fg = momiji.palette.black, bg = momiji.palette.red, empha = { "bold", "undercurl" }, guisp = momiji.palette.blue, blend = 0.3 })
    end)
  end)
end)
